version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/api
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: main

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: main
    ports:
      - "3306:3306"

    command: --bind-address=0.0.0.0

